AllCops:
  TargetRubyVersion: 2.3
  Exclude:
    - '_todelete/**/*'
    - 'vendor/**/*'
    - 'db/schema.rb'
    - 'client_app/node_modules/**/*'
    - 'node_modules/**/*'
    - 'db/*'
    - 'db/fixtures/**/*'
    - 'tmp/**/*'
    - 'bin/**/*'
    - 'builds/**/*'
Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 120
  Exclude:
    - 'script/**/*'
Metrics/ClassLength:
  Max: 1000
Metrics/MethodLength:
  Max: 20
Metrics/BlockLength:
  Enabled: true
  Exclude:
    - 'spec/**/*'

Style/RedundantSelf:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
Style/FrozenStringLiteralComment:
  EnforcedStyle: never
Style/NumericPredicate:
  EnforcedStyle: comparison
Style/StringLiterals:
  EnforcedStyle: double_quotes
Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes
Style/TrailingCommaInLiteral:
  EnforcedStyleForMultiline: comma
Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma

Layout/MultilineArrayBraceLayout:
  EnforcedStyle: new_line
Layout/MultilineHashBraceLayout:
  EnforcedStyle: new_line
Layout/MultilineMethodCallBraceLayout:
  EnforcedStyle: new_line
Layout/MultilineMethodDefinitionBraceLayout:
  EnforcedStyle: new_line
Layout/AlignParameters:
  EnforcedStyle: with_fixed_indentation
Layout/MultilineOperationIndentation:
  EnforcedStyle: indented
Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented
